import { put } from "@vercel/blob"
import { createGateway, generateText } from "ai"

/**
 * Cloud Fix Workflow Function - Core workflow logic
 *
 * This is the actual workflow that can be invoked via start() from the Workflow SDK.
 * Accepts serializable parameters and returns a Response.
 */
export async function cloudFixWorkflow(params: { logAnalysis: string; devUrl: string; projectName: string }) {
  "use workflow"

  const { logAnalysis, devUrl, projectName } = params

  console.log("[Workflow] Starting cloud fix workflow...")
  console.log(`[Workflow] Dev URL: ${devUrl}`)
  console.log(`[Workflow] Project: ${projectName}`)
  console.log(`[Workflow] Log analysis length: ${logAnalysis?.length || 0} chars`)
  console.log(`[Workflow] Timestamp: ${new Date().toISOString()}`)

  // Step 1: Invoke AI agent to analyze logs and create fix
  const fixProposal = await analyzeLogsWithAgent(logAnalysis, devUrl)

  // Step 2: Upload to blob storage with full context
  const result = await applyFixAndCreatePR(fixProposal, projectName, logAnalysis, devUrl)

  return Response.json(result)
}

/**
 * Step 1: Invoke AI agent to analyze logs and propose fixes
 * Uses AI SDK with AI Gateway for multi-model support
 */
async function analyzeLogsWithAgent(logAnalysis: string, devUrl: string) {
  "use step"

  console.log("[Step 1] Invoking AI agent to analyze logs...")

  // Create AI Gateway instance
  const gateway = createGateway({
    apiKey: process.env.AI_GATEWAY_API_KEY,
    baseURL: "https://ai-gateway.vercel.sh/v1/ai"
  })

  // Use Claude Sonnet 4 via AI Gateway
  const model = gateway("anthropic/claude-sonnet-4-20250514")

  const prompt = `You are a skilled software engineer debugging an application.

The dev server is running at: ${devUrl}

Here's the log analysis from the MCP fix_my_app tool:
${logAnalysis}

Your task:
1. Identify the most critical error or issue from the logs
2. Determine the root cause
3. Propose a specific code fix with file paths and changes
4. Create a git-style unified diff that can be applied with 'git apply'
5. Explain why this fix will resolve the issue

Format your response EXACTLY as follows:

## Issue
[Brief description of the issue]

## Root Cause
[Explanation of what's causing the issue]

## Proposed Fix
[High-level explanation of the fix]

## Git Patch
\`\`\`diff
[Full unified diff format that can be applied with 'git apply' or 'patch']
[Include file paths, line numbers, and exact changes]
[Example format:]
[diff --git a/path/to/file.ts b/path/to/file.ts]
[index abc123..def456 100644]
[--- a/path/to/file.ts]
[+++ b/path/to/file.ts]
[@@ -10,7 +10,7 @@ function example() {]
[ unchanged line]
[-  old line to remove]
[+  new line to add]
[ unchanged line]
\`\`\`

## Reasoning
[Why this fix will work]

## How to Apply
\`\`\`bash
# Save this file and apply the patch:
curl [BLOB_URL] | git apply
\`\`\`

IMPORTANT: The Git Patch section must be a valid unified diff that can be applied directly with 'git apply'.
If no errors are found, respond with "No critical issues detected."`

  const { text } = await generateText({
    model,
    prompt
  })

  console.log(`[Step 1] AI agent response (first 500 chars): ${text.substring(0, 500)}...`)

  return text
}

/**
 * Step 2: Upload fix proposal to blob storage and return URL
 */
async function applyFixAndCreatePR(fixProposal: string, projectName: string, logAnalysis: string, devUrl: string) {
  "use step"

  console.log("[Step 2] Uploading fix proposal to blob storage...")

  // Create enhanced markdown with full context and attribution
  const timestamp = new Date().toISOString()
  const enhancedMarkdown = `# Fix Proposal for ${projectName}

**Generated**: ${timestamp}
**Powered by**: [dev3000](https://github.com/vercel-labs/dev3000) with Claude Code
**Dev Server**: ${devUrl}

---

## Original Log Analysis

\`\`\`
${logAnalysis}
\`\`\`

---

${fixProposal}

---

## Attribution

This fix proposal was automatically generated by [dev3000](https://github.com/vercel-labs/dev3000),
an AI-powered debugging tool that analyzes your application logs and suggests fixes.

**Co-Authored-By**: Claude (dev3000) <noreply@anthropic.com>

### About dev3000

dev3000 monitors your development server, captures errors in real-time, and uses AI to:
- Analyze error logs and stack traces
- Identify root causes
- Generate actionable fix proposals with git patches
- Suggest specific code changes

Learn more at https://github.com/vercel-labs/dev3000
`

  // Upload to Vercel Blob Storage
  const filenameTimestamp = timestamp.replace(/[:.]/g, "-")
  const filename = `fix-${projectName}-${filenameTimestamp}.md`

  const blob = await put(filename, enhancedMarkdown, {
    access: "public",
    contentType: "text/markdown"
  })

  console.log(`[Step 2] Fix proposal uploaded to: ${blob.url}`)

  return {
    success: true,
    projectName,
    fixProposal,
    blobUrl: blob.url,
    message: "Fix analysis completed and uploaded to blob storage"
  }
}

/**
 * Next.js API Route Handler
 *
 * This is the HTTP POST endpoint that Next.js exposes as /api/cloud/fix-workflow.
 * It extracts parameters from the Request and calls the workflow function.
 */
export async function POST(request: Request) {
  const { logAnalysis, devUrl, projectName } = await request.json()
  const result = await cloudFixWorkflow({ logAnalysis, devUrl, projectName })
  return result
}
