packages:
  - www
  - mcp-server

catalog:
  "@tailwindcss/postcss": ^4.1.9
  "@types/node": ^22.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  autoprefixer: ^10.4.20
  next: 15.5.1-canary.30
  postcss: ^8.5
  react: 19.2.0-canary-de5a1b20-20250905
  react-dom: 19.2.0-canary-de5a1b20-20250905
  tailwindcss: ^4.1.9
  typescript: ^5.0.0
  zod: ^3.22.4

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
